name: Deploy AWS Lambda

on:
  push: # every time we push to main branch, any changes within /lambda triggers lambda deploy workflow(ie. changes to lambda_function)
    branches:
      - main
    paths:
      - 'lambda/'

jobs:
  deploy-lambda: # Job name
    runs-on: ubuntu-latest # Specifies the runner type
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python # Sets up python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install Dependencies # Installs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS Creds # Sets up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Lambda Function #Zips lambda director and updates lambda function
        run: |
          cd lambda/
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
